export const CountryCodes = [
    { code: 1, name: 'India' },
    { code: 14, name: 'Australia' },
    { code: 30, name: 'Brazil' },
    { code: 37, name: 'Canada' },
    { code: 94, name: 'Indonesia' },
    { code: 148, name: 'New Zealand' },
    { code: 162, name: 'Philippines' },
    { code: 166, name: 'Qatar' },
    { code: 184, name: 'Singapore' },
    { code: 189, name: 'South Africa' },
    { code: 191, name: 'Sri Lanka' },
    { code: 208, name: 'Turkey' },
    { code: 214, name: 'UAE' },
    { code: 215, name: 'United Kingdom' },
    { code: 216, name: 'United States' },
  ];